language: php
php:
  - nightly
  - '7.1'
  - '7.0'
install:
  - composer install
script:
  - composer lint
  - composer test
  - composer docs
deploy:
  overwrite: true
  provider: pages
  file_glob: true
  file: docs/*
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    php: '7.0'
