sudo: required
language: php
php:
  - nightly
  - '7.1'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
install:
  - composer install
  - composer update
script:
  - composer lint
  - composer test:coverage-clover
  - composer docs
after_success:
  - bash <(curl -s https://codecov.io/bash) -f tests/unit/coverage/coverage.xml
deploy:
  overwrite: true
  provider: pages
  file_glob: true
  file: docs/*
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    php: '7.1'
